### ISSUE TITLE
Add New Organizational Chart

### ISSUE THREAD

**Issue by mrpeppapig** [workpebojot/udms#2]
- [x] Done

**Comment by workpebojot** [comment]
Related commits not related to (issue #1):
- 9648fe6
- f766e5c
- 3cfc13e
- f6b3e26
- afd2abd
- 7873467
- c4a38d8

**Comment by workpebojot** [comment]
List of commits related to issue (#2):
- 91ec81d 5257958 ec8a620 27b85f8 fab6aaf 3b9c

**Comment by mrpeppapig** [comment]
List of commits related to issue (#2):
- 91ec81d
- 5257958
- ec8a620
- 27b85f8
- fab6aaf
- 3b9cea2
- 5b46ca0
